config = {
    'replay_buffer': 'per',
    'buffer_capacity': 100000,
    'n_step': 3,
    'gamma': 0.99,
    'hidden_dim': 256,
    'target_networks': True,
    'critic_type': 'basic',
    'num_points': 51,
    'support_range': (-10, 10),
    'critic_lr': 1e-3,
    'actor_lr': 1e-3,
    'mean_lr': 1e-3,
    'std_lr': 1e-3,
    'tau': 0.005,
    'seed': 0,
    'per_alpha': 0.6,
    'action_min': 0,
    'action_max': 1,
    'kl_constraint_mean': 0.1,
    'kl_constraint_std': 0.1,
    'kl_constraint_temperature': 0.1,
    'save_model_interval': 10,
    'beta': 0.4,
    'beta_decay': 0.001,
    'action_sample_size': 10
}